This notebook offers a bit of a deeper dive into the numpy functions discussed during this tutorial. 
MGrid, Tile, and Stack.
This is just a much simpler look at these functions.

In [1]:
import cv2
import numpy as np

In [2]:
def display(img):
    cv2.imshow('image',img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

First, we are going to create a very small 4x4 matrix, which will represent out image.  
This matrix will have shape 4,4,3 - representing an RGB image.

In [14]:
matrix = np.random.randint(255, size=(4,4,3))
print(matrix.shape)
print(matrix)

(4, 4, 3)
[[[161 239  53]
  [ 53 169  91]
  [136 231   0]
  [166  12  76]]

 [[ 63 122 153]
  [135 235  41]
  [ 75 102 242]
  [ 81 189 106]]

 [[152  19 136]
  [109  92 140]
  [124 206 147]
  [229 128  31]]

 [[ 96 115 102]
  [134  24 162]
  [178 253  63]
  [113  34 252]]]


In [16]:
# create an opencv image
img = matrix.astype(np.uint8)
# for display purposes, resize
img = cv2.resize(img, (400,400))
display(img)
# wow, it looks really nice!

First up: let's discuss mgrid.
MGrid takes in 3 positional arguments, in the manner x:y:z  
It is called like this - new_grid = np.mgrid[x:y:z]  
MGrid creates a 1-D array with dimensions as specified by x:y:z, where *x* is the inclusive low value, *y* the exlcusive high value, and *z* the increments. The size of the array is defined by how many increments of *z* there are between *x* and *y*.

In [17]:
# we would expect this to have 5 values
np.mgrid[20:101:20]

array([ 20,  40,  60,  80, 100])

In [26]:
# to work with our 4x4 matrix, we will need to create a single mgrid of length 4.
# we will consider the values percentages, and go from 40% to 80%. 
# since the top is not inclusive, we may expect it to not reach that actual value.
inc = (81-40) / 4
print(inc)
mgrid = np.mgrid[40:80:inc]
print(mgrid)

10.25
[40.   50.25 60.5  70.75]


Now that we have our grid, we can discuss the next numpy function: Tile  

We can use numpy's tile to extend our 1-D array into an N-D array. It constructs an array by repeating the given array by the amount of time the size is given. As you can see below, inputting size (4,1) returns the grid we were looking for, a 4x4.  
As tile repeats the 1-D array, each row is the same, meaning the percentages increase from left-right in this grid.


In [28]:
tile_2d = np.tile(mgrid, (4,1))
print(tile_2d.shape)
print(tile_2d)

(4, 4)
[[40.   50.25 60.5  70.75]
 [40.   50.25 60.5  70.75]
 [40.   50.25 60.5  70.75]
 [40.   50.25 60.5  70.75]]


Next up is numpy's stack. Stack allows us to join a sequence of arrays, along a new axis.  
This means we could stack our mgrid along a different axis, to create a 4x4 grid where the percent change goes from top to bottom. The only thing is, the np.stack function only takes in a tuple of arrays.  
To create the proper stack, we will need to first create a tuple of our mgrid 4 repeated 4 times, then apply stack to it. Finally, we will need to transpose the created shape.


In [35]:
# create a list (mutable object), before converting to tuple (immutable)
tu = []
for i in range(4):
    tu.append(mgrid)
tu = tuple(tu)
stack = np.stack(tu).T
print(stack.shape, '\n', stack)

(4, 4) 
 [[40.   40.   40.   40.  ]
 [50.25 50.25 50.25 50.25]
 [60.5  60.5  60.5  60.5 ]
 [70.75 70.75 70.75 70.75]]
